name: Build and Push Image

on:
  workflow_call:
    inputs:
      environment:
        description: Define which GitHub Environment to use
        required: true
        type: string
    secrets:
      SERVICE_PASSWORD:
        required: true

jobs:
  build_and_push:
    runs-on: arc
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY_URL }}
          username: ${{ vars.SERVICE_USER }}
          password: ${{ secrets.SERVICE_PASSWORD }}
      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY_URL }}/${{ vars.SERVICE_USER }}/step-api:latest
            ${{ vars.DOCKER_REGISTRY_URL }}/${{ vars.SERVICE_USER }}/step-api:${{ github.sha }}
            ${{ startsWith(github.ref, 'refs/tags/') && format('{0}/{1}/step-api:{2}', vars.DOCKER_REGISTRY_URL, vars.SERVICE_USER, github.ref_name) || '' }}
